"""Публичный API клиентского стека vkx: VKClient, токены, хранилище, HTTP."""

from .client import (
    DEFAULT_GROUP_INTERVAL,
    DEFAULT_USER_INTERVAL,
    EXECUTE_BATCH_LIMIT,
    EXECUTE_CODE_BYTES_LIMIT,
    PendingApiCall,
    VKClient,
    VKError,
)
from .http import API_HOST, API_VERSION, HttpClient, HttpResponse
from .pagination import (
    DEFAULT_PAGINATION_LIMIT,
    PAGINATION_LIMITS,
    limit_for,
    merge_pages,
    paginate,
)
from .storage import (
    JSONStore,
    MemoryStore,
    SQLiteStore,
    State,
    Store,
    default_store,
    open_store,
)
from .tokens import (
    CATEGORY_SCOPES,
    SCOPE_TITLES,
    StaticTokenSource,
    TokenSource,
    TokenSourceError,
    WebCookieSource,
    method_scope,
    scope_keys,
    scope_titles,
    validate_web_cookies,
)

__all__ = [
    "API_HOST",
    "API_VERSION",
    "CATEGORY_SCOPES",
    "DEFAULT_GROUP_INTERVAL",
    "DEFAULT_PAGINATION_LIMIT",
    "DEFAULT_USER_INTERVAL",
    "EXECUTE_BATCH_LIMIT",
    "EXECUTE_CODE_BYTES_LIMIT",
    "PAGINATION_LIMITS",
    "SCOPE_TITLES",
    "HttpClient",
    "HttpResponse",
    "JSONStore",
    "MemoryStore",
    "PendingApiCall",
    "SQLiteStore",
    "State",
    "StaticTokenSource",
    "Store",
    "TokenSource",
    "TokenSourceError",
    "VKClient",
    "VKError",
    "WebCookieSource",
    "default_store",
    "limit_for",
    "merge_pages",
    "method_scope",
    "open_store",
    "paginate",
    "scope_keys",
    "scope_titles",
    "validate_web_cookies",
]
