from vkx.models.methods.account import *
from vkx.models.methods.ads import *
from vkx.models.methods.app_widgets import *
from vkx.models.methods.apps import *
from vkx.models.methods.auth import *
from vkx.models.methods.base_category import *
from vkx.models.methods.board import *
from vkx.models.methods.bugtracker import *
from vkx.models.methods.database import *
from vkx.models.methods.docs import *
from vkx.models.methods.donut import *
from vkx.models.methods.downloaded_games import *
from vkx.models.methods.fave import *
from vkx.models.methods.friends import *
from vkx.models.methods.gifts import *
from vkx.models.methods.groups import *
from vkx.models.methods.lead_forms import *
from vkx.models.methods.likes import *
from vkx.models.methods.market import *
from vkx.models.methods.messages import *
from vkx.models.methods.newsfeed import *
from vkx.models.methods.notes import *
from vkx.models.methods.notifications import *
from vkx.models.methods.orders import *
from vkx.models.methods.pages import *
from vkx.models.methods.photos import *
from vkx.models.methods.podcasts import *
from vkx.models.methods.polls import *
from vkx.models.methods.pretty_cards import *
from vkx.models.methods.search import *
from vkx.models.methods.secure import *
from vkx.models.methods.stats import *
from vkx.models.methods.status import *
from vkx.models.methods.storage import *
from vkx.models.methods.store import *
from vkx.models.methods.stories import *
from vkx.models.methods.streaming import *
from vkx.models.methods.translations import *
from vkx.models.methods.users import *
from vkx.models.methods.utils import *
from vkx.models.methods.video import *
from vkx.models.methods.wall import *
from vkx.models.methods.widgets import *
